### ISSUE TITLE
Add s/n (signal to noise) to Plane.Metrics

### ISSUE THREAD

**Issue by DaftPict** [opencadc/caom2#113]
We have a new spectroscopic initiative for JWST work which would require having the observation signal to noise ratio (float value) available in the model. The obvious place is to add it to the plane.metrics class. Would it be possible to get this in v2.4 since it is a pretty simple addition?

**Comment by pdowler** [comment]
http://www.opencadc.org/caom2/#Metrics

The current  model includes fluxDensityLimit and magLimit which are defined as essentially "brightness of a source with S:N of 10". The interoperable profile claims the units of fluxDensityLimit is Jy but it should probably be jansky per square degree (Jy deg-2)... that and magLimit are clearly defined and aimed at characterising sources in images, but they are related to signal-to-noise and detection limits.

If we want something analaguous for spectral features I gyess it would be something like "how strong a feature to have a S:N of X" and we'd have to define it to work for both emission and absorption features.

I asked an astronomer at CADC about S:N of spectra and he would define it as the S:N of the continuum (so find some part of the spectrum with no lines and measure it there. Is that the desired concept here?

**Comment by ijiraq** [comment]
My reading here is that we should allow a new metric of 'PeakSNRofContinuum' and there will need some engineering to determine how that is computed.  But, for Spectra searches being able to say PeakSNRofContinuum > 1000 would be useful and complementry to fluxDensityLimit .  I think, BTW, that fluxDensityLimit given in Jy is correct, that the limit of the faintest sources you can detect in the image, not the faintest surface brightness you can detect (which is more akin to the SNRofContinuum I suppose).

**Comment by pdowler** [comment]
Is  'PeakSNRofContinuum' only applicable to data with a spectral axis or can it be defined to be computable/measureable for images?

And why "peak" and not just snrContinuum?

**Comment by ijiraq** [comment]
The SNR of Continuum will vary with wavelength and be quite low at spectral sensitivity boundaries.  Also, the Continuum will vary with wavelength. 

Could be 'medium' instead I guess but peak is more straightforward.  Check with DB?

I think this is only for Spectral data types.  For image type one could give a SNR and FluxLimit with the FluxLimit being the limit of detection at the given SNR.   Currently we just give the Flux Limit and people need to assume this is at some reasonable SNR (like 5 or something) without getting too tied up.  For discovery archive searches I expect that flux limit is sufficient for imaging.

**Comment by DaftPict** [comment]
The use case I was given would be using the average snr per pixel over a specified wavelength range (it's low res. spectroscopy).  It would be very complex to try and describe all the possible ways to define/compute snr for all the different types of spectroscopy so I'd suggest that we just keep it simple for now and provide a single field and we populate it (or not) with a value that is defined by the telescope/instrument/target/proposal intent? I think that is sufficient for discovery...

**Comment by pdowler** [comment]
Going to name this sampleSNR to be somewhat symmetric with using sampleSize to indicate what is usually pixel size but could be something else (eg in an aggregated time series built from combining spectra and photometry measurements and "pxiel" is too specific). The definition/docs will say it is S:N per sample, possibly aggregated over a subset or all samples in the data so that it is representattive.
