### ISSUE TITLE
SUBARU resolver URL encodes the necessary query parameter

### ISSUE THREAD

**Issue by at88mph** [opencadc/caom2#157]
The `frameinfo=<YYYY-MM-DD>/<FRAMEID>` format is being URL encoded by the `SubaruResolver` class.  When a user requests SUBARU data from the browser, it also encodes it which results in a double-encoded value and is unreadable.

**Comment by pdowler** [comment]
I still think the resolver is doing the right thing here (in the generla case) so this is not a bug. It might be unnecessary for some values, but it's never wrong.

**Comment by pdowler** [comment]
cannot reproduce
