### ISSUE TITLE
resolve smoka artifact URIs.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/caom2#50]
The artifact URIs for the smoka observation records need to be resolved.  

To get data make a POST request as shown in this example: 
[data requests](https://gist.github.com/ijiraq/1ad22eda4517ac6644dd13846de71408)

To get preview PNG files make a get request on the service as described here:
[preview requests](https://gist.github.com/ijiraq/dcdea117b8e32fee9aef865db858cb13)

**Comment by pdowler** [comment]
SmokaResolver implemented and released
