### ISSUE TITLE
fits2caom2 help is inaccurate.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/caom2#8]
The -help content suggest that -test does not persist to the database but really -test turns off writing to a file.  

Are there cases where fits2caom2 writes to a database anymore?  

option A:  remove -test but that might break code that expects -test

option B: Change the behaviour so -test still writes the .xml (also might break current usgage)

option C:  Change the help line to indicate that no file will be write to -out, impacts likely minimal.

**Comment by pdowler** [comment]
There is no useful test mode now that fits2caom2 only writes xml files. Will remove it.

**Comment by pdowler** [comment]
WNF (will not fix) since this software is deprecated and only bugs effecting operations are addressed.
