### ISSUE TITLE
Move target name to the plane level

### ISSUE THREAD

**Issue by andamian** [opencadc/caom2#97]
For ALMA, product planes could refer to separate targets and the target name at the observation level is not sufficient.

**Comment by pdowler** [comment]
analysis: the more general concept here is that an observation may acquire data about many targets and data for individual targets could be extracted into separate products (planes)... In addition to ALMA data, this seems directly applicable to instruments like multi-object spectrograph and indirectly supports various re-packaging of data based on detected  features (objects, spectral features, etc).

Having target in two places in the model and usable for data discovery queries is probably going to be confusing and make for extra ugly queries so it seems better to eventually move target.  We could add target to plane and deprecate Observation.target and document that the latter is only used when Plane.target is null.

By itself, adding optional Plane.target would not invalidate any existing metaChecksum values.  Moving target from Observation to Plane would invalidate metaChecksums (requires re-ingest).

**Comment by pdowler** [comment]
The change of CompositeObservation to DerivedObservation provides an alt pattern for this use case.
